options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Passo 1: Obter o segredo do Secret Manager e autenticar
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Authenticate Service Account"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Baixar o segredo e salvar em um arquivo JSON
        gcloud secrets versions access latest --secret="service-account-key" > /workspace/service_account_key.json
        gcloud auth activate-service-account --key-file=/workspace/service_account_key.json
        gcloud config set project azure-integration-405515

  
  # Passo 3: Criar o projeto na Organization B
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Create Project"
    args:
      - "gcloud"
      - "projects"
      - "create"
      - "${_NEW_PROJECT_ID}"
      - "--organization=${_ORGANIZATION_ID_B}"
      - "--labels=created-by=cloud-build"

substitutions:
  _NEW_PROJECT_ID: "new-project-id"  # Substitua pelo ID desejado do novo projeto
  _ORGANIZATION_ID_B: "653492276671"  # Substitua pelo ID da Organization B

timeout: "600s"  # Ajuste conforme necessário
