steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone https://github.com/Hyti-CET/project-factory.git && cd seu-repositorio

- name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init && terraform apply -var "project_name=p-${_PROJECT_NAME}" -var "owner_email=${_OWNER_EMAIL}" -auto-approve

timeout: '1200s'  # Timeout de 20 minutos

substitutions:
  _PROJECT_NAME: 'nome-do-projeto'
  _OWNER_EMAIL: 'email-do-solicitante'

serviceAccount: 'SERVICE_ACCOUNT@SEU_PROJETO.iam.gserviceaccount.com'
